const JOBS_DATA = [
  {
    id: "job-001",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/2544211/software-development-engineer-intern",
    description: "Join our team as an SDE Intern and work on large-scale distributed systems. You will collaborate with senior engineers to build features that impact millions of customers globally. Perfect for final year students with strong CS fundamentals."
  },
  {
    id: "job-002",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "PL/SQL", "Aptitude"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3.5–4.5 LPA",
    applyUrl: "https://www.tcs.com/careers/india/graduate-engineer-trainee",
    description: "TCS is looking for GETs to join our various business units. This is a great opportunity for fresh graduates to start their career in a global IT services firm. Training in latest technologies will be provided."
  },
  {
    id: "job-003",
    title: "Junior Backend Developer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Node.js", "Express", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "10–15 LPA",
    applyUrl: "https://swiggy.wd3.myworkdayjobs.com/en-US/Swiggy/job/Engineering-Backend-Developer",
    description: "Build robust APIs and microservices that power the Swiggy delivery ecosystem. You will work on scaling our backend to handle thousands of requests per second. Experience with distributed systems is a plus."
  },
  {
    id: "job-004",
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "TypeScript", "Tailwind CSS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://razorpay.com/jobs/frontend-intern",
    description: "Work with our design and engineering teams to build beautiful and intuitive payment interfaces. You will learn how to build production-ready React applications. Passion for UI/UX is essential."
  },
  {
    id: "job-005",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Tableau", "Excel"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://flipkart.com/careers/jobs/data-analyst-intern",
    description: "Analyze customer data to generate insights that drive business decisions. You will work with large datasets and learn advanced SQL and data visualization techniques. Strong analytical mind required."
  },
  {
    id: "job-006",
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "4–6 LPA",
    applyUrl: "https://infosys.com/careers/java-developer",
    description: "Develop enterprise-grade Java applications for our global clients. You will be part of an agile team and contribute to all phases of the development lifecycle. Good communication skills are a must."
  },
  {
    id: "job-007",
    title: "Python Developer (Fresher)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://wipro.com/careers/python-developer",
    description: "Join Wipro as a Python Developer and work on innovative projects in AI and Automation. You will write clean, scalable code and collaborate with cross-functional teams. Enthusiasm to learn is highly valued."
  },
  {
    id: "job-008",
    title: "React Developer (1-3)",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Redux", "JavaScript", "HTML/CSS"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "12–18 LPA",
    applyUrl: "https://zomato.com/careers/react-developer",
    description: "Craft amazing user experiences for Zomato's millions of users. You will build high-performance web applications and ensure seamless integration with our backend services. Attention to detail is key."
  },
  {
    id: "job-009",
    title: "QA Intern",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Java"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹20k/month Internship",
    applyUrl: "https://cognizant.com/careers/qa-intern",
    description: "Learn the fundamentals of software quality assurance. You will participate in test planning, execution, and bug tracking. This is a great starting point for a career in software testing."
  },
  {
    id: "job-010",
    title: "Full Stack Engineer",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "14–22 LPA",
    applyUrl: "https://paytm.com/careers/fullstack-engineer",
    description: "Build the future of digital payments in India. You will work on both frontend and backend systems, ensuring high availability and security. Looking for polyglot engineers who love to build."
  },
  {
    id: "job-011",
    title: "iOS Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "3-5",
    skills: ["Swift", "iOS SDK", "SwiftUI", "Combine"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "25–35 LPA",
    applyUrl: "https://phonepe.com/careers/ios-developer",
    description: "Join the team that builds India's most popular payment app. You will develop complex iOS features and work on app performance and stability. 3+ years of experience with Swift is required."
  },
  {
    id: "job-012",
    title: "Systems Engineer",
    company: "IBM",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Linux", "Bash", "Networking", "Security"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "5–8 LPA",
    applyUrl: "https://ibm.com/careers/systems-engineer",
    description: "Manage and optimize our enterprise IT infrastructure. You will work on system administration, security hardening, and performance tuning. Strong fundamentals in operating systems are essential."
  },
  {
    id: "job-013",
    title: "DevOps Intern",
    company: "Capgemini",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["AWS", "Docker", "Kubernetes", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹18k–₹25k/month Internship",
    applyUrl: "https://capgemini.com/careers/devops-intern",
    description: "Get hands-on experience with modern cloud infrastructure. You will assist in CI/CD pipeline automation and container orchestration. Passion for automation and infrastructure-as-code is a must."
  },
  {
    id: "job-014",
    title: "Android Developer",
    company: "Cure.fit",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Kotlin", "Android SDK", "Jetpack Compose"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "15–20 LPA",
    applyUrl: "https://curefit.com/careers/android-developer",
    description: "Scale our health and fitness app to millions of users. You will build new features in Kotlin and ensure smooth animations and peak performance. Experience with Jetpack Compose is preferred."
  },
  {
    id: "job-015",
    title: "Database Administrator",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "3-5",
    skills: ["Oracle DB", "SQL", "Performance Tuning"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "18–28 LPA",
    applyUrl: "https://oracle.com/careers/dba",
    description: "Ensure the reliability and performance of our global database systems. You will work on database design, migration, and performance optimization. Expert knowledge of Oracle DB is required."
  },
  {
    id: "job-016",
    title: "Web Developer Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "PHP"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://zoho.com/careers/web-developer-intern",
    description: "Support our web development team in building and maintaining Zoho's products. You will work on various small to medium scale features. Looking for quick learners with a passion for web technologies."
  },
  {
    id: "job-017",
    title: "UI/UX Designer",
    company: "CRED",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Figma", "Sketch", "Prototyping"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "18–25 LPA",
    applyUrl: "https://cred.club/careers/designer",
    description: "Join the most design-forward startup in India. You will create stunning visual designs and seamless user flows. We value creativity, experimentation, and a deep understanding of user behavior."
  },
  {
    id: "job-018",
    title: "ML Engineer Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "TensorFlow", "Pandas", "Scikit-Learn"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://freshworks.com/careers/ml-intern",
    description: "Apply machine learning to improve our customer support and sales products. You will help build and fine-tune models that power our AI features. Strong background in math and statistics is preferred."
  },
  {
    id: "job-019",
    title: "Golang Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Go", "Distributed Systems", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "16–24 LPA",
    applyUrl: "https://juspay.in/careers/golang-developer",
    description: "Write high-performance backend systems in Go. You will solve complex problems in payments and concurrency. We value engineers who are focused on writing clean, efficient, and reliable code."
  },
  {
    id: "job-020",
    title: "Business Analyst",
    company: "Accenture",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Excel", "SQL", "PowerBI", "Communication"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "8–12 LPA",
    applyUrl: "https://accenture.com/careers/business-analyst",
    description: "Bridge the gap between business requirements and technical solutions. You will work with clients to understand their needs and transform them into actionable insights for our development teams."
  },
  {
    id: "job-021",
    title: "Cloud Architect",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "5+",
    skills: ["AWS", "Azure", "Cloud Infrastructure", "Kubernetes"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "35–50 LPA",
    applyUrl: "https://sap.com/careers/cloud-architect",
    description: "Design and implement scalable cloud architectures for our enterprise software products. You will lead cloud migration efforts and optimize infrastructure costs. 5+ years of cloud experience required."
  },
  {
    id: "job-022",
    title: "Ruby on Rails Developer",
    company: "Freshdesk",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Ruby", "Rails", "MySQL", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "12–18 LPA",
    applyUrl: "https://freshworks.com/freshdesk/job",
    description: "Maintain and enhance the core Freshdesk product. You'll join an expert team of Rails developers and help scale our support software to millions of businesses. Solid RoR experience is a must."
  },
  {
    id: "job-023",
    title: "Cyber Security Analyst",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Security Protocols", "Ethical Hacking", "Firewalls"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "10–16 LPA",
    applyUrl: "https://dell.com/careers/security-analyst",
    description: "Protect our systems and data from cyber threats. You will conduct vulnerability assessments, monitor network traffic, and respond to security incidents. Certifications like CEH or CISSP are a plus."
  },
  {
    id: "job-024",
    title: "Product Manager Intern",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Product Roadmap", "Analytics", "User Research"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://ola.com/careers/pm-intern",
    description: "Work closely with our product leads to define and launch new features for Ola. You will conduct user research, analyze data, and help manage the product lifecycle. Great for budding PMs."
  },
  {
    id: "job-025",
    title: "Site Reliability Engineer",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "3-5",
    skills: ["Python", "Azure", "Terraform", "Monitoring"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "30–45 LPA",
    applyUrl: "https://microsoft.com/careers/sre",
    description: "Ensure the reliability and performance of Microsoft's online services. You will build automation and tools that help us manage our vast cloud infrastructure. Looking for strong systems thinkers."
  },
  {
    id: "job-026",
    title: "Content Writer (Tech)",
    company: "HackerRank",
    location: "Remote",
    mode: "Remote",
    experience: "1-3",
    skills: ["Technical Writing", "SEO", "Engineering Knowledge"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–9 LPA",
    applyUrl: "https://hackerrank.com/careers/writer",
    description: "Write high-quality technical content for our blog and developer resources. You should have a solid understanding of computer science concepts and the ability to explain them clearly and concisely."
  },
  {
    id: "job-027",
    title: "Embedded Systems Engineer",
    company: "Qualcomm",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "1-3",
    skills: ["C", "RTOS", "Bluetooth", "IoT"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "14–22 LPA",
    applyUrl: "https://qualcomm.com/careers/embedded-engineer",
    description: "Develop software for Qualcomm's world-leading mobile and IoT chipsets. You will work on low-level firmware and device drivers. Strong knowledge of computer architecture and C is required."
  },
  {
    id: "job-028",
    title: "Social Media Manager",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Content Strategy", "Digital Marketing", "Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "7–11 LPA",
    applyUrl: "https://unacademy.com/careers/social-media",
    description: "Build and manage Unacademy's social media presence. You will create engaging content and grow our community across various platforms. Creativity and a social-first mindset are essential."
  },
  {
    id: "job-029",
    title: "Blockchain Developer",
    company: "Polygon (Matic)",
    location: "Remote",
    mode: "Remote",
    experience: "1-3",
    skills: ["Solidity", "Ethereum", "DApps", "Web3"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "20–35 LPA",
    applyUrl: "https://polygon.technology/careers/blockchain-dev",
    description: "Join the team that is scaling Ethereum to millions of users. You will build and audit smart contracts and contribute to our ecosystem of decentralized apps. Passion for Web3 is required."
  },
  {
    id: "job-030",
    title: "SDR / Sales Intern",
    company: "Chargebee",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Communication", "Lead Generation", "CRM"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://chargebee.com/careers/sales-intern",
    description: "Learn the ropes of B2B SaaS sales. You'll assist our sales team in researching and reaching out to potential customers. Great opportunity to develop communication and persuasion skills."
  },
  {
    id: "job-031",
    title: "Machine Learning Engineer",
    company: "Amazon Web Services",
    location: "Bangalore",
    mode: "Onsite",
    experience: "3-5",
    skills: ["Python", "PyTorch", "SageMaker", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "35–55 LPA",
    applyUrl: "https://amazon.jobs/aws/ml-engineer",
    description: "Help customers build and deploy production ML models on AWS. You will work on cutting-edge generative AI and computer vision projects. Deep theoretical and practical knowledge of ML is a must."
  },
  {
    id: "job-032",
    title: "Backend Intern (Go)",
    company: "Udaan",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Golang", "NoSQL", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://udaan.com/careers/intern",
    description: "Build scalable commerce infrastructure for India's B2B marketplace. You'll get to write high-performance Go code and learn how to manage complex microservice architectures at scale."
  },
  {
    id: "job-033",
    title: "Customer Support Specialist",
    company: "Instamojo",
    location: "Remote",
    mode: "Remote",
    experience: "0-1",
    skills: ["Empathy", "Troubleshooting", "Support Tools"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–6 LPA",
    applyUrl: "https://instamojo.com/careers/support",
    description: "Help our small business customers succeed by providing excellent support. You'll solve technical issues and guide users through our platform. Strong written and verbal communication is key."
  },
  {
    id: "job-034",
    title: "Flutter Developer",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Flutter", "Dart", "Firebase", "State Management"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "14–22 LPA",
    applyUrl: "https://groww.in/careers/flutter-dev",
    description: "Build beautiful and high-performance cross-platform apps for Groww. You'll work on the investment platform used by millions. Experience with Flutter and state management is essential."
  },
  {
    id: "job-035",
    title: "Network Engineer",
    company: "Cisco",
    location: "Bangalore",
    mode: "Onsite",
    experience: "3-5",
    skills: ["Cisco IOS", "BGP/OSPF", "Routing", "Switching"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "16–25 LPA",
    applyUrl: "https://cisco.com/careers/network-engineer",
    description: "Design and maintain large scale enterprise networks. You'll work with the latest Cisco networking hardware and software. CCNA/CCNP certification is highly preferred."
  },
  {
    id: "job-036",
    title: "Data Scientist",
    company: "Mu Sigma",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Statistics", "R/Python", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–9 LPA",
    applyUrl: "https://mu-sigma.com/careers",
    description: "Apply your analytical skills to solve complex business problems for Fortune 500 companies. You will participate in all stages of the decision science lifecycle. Strong curiosity is valued."
  },
  {
    id: "job-037",
    title: "Product Designer Intern",
    company: "InMobi",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Visual Design", "User Testing", "Figma"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://inmobi.com/careers/designer-intern",
    description: "Join the product design team at India's first unicorn. You'll help design mobile-first advertising products and create intuitive user interfaces. Portfolio showing your process is required."
  },
  {
    id: "job-038",
    title: "Security Engineer (AppSec)",
    company: "BigBasket",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["OWASP", "Penetration Testing", "Scripts"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "12–20 LPA",
    applyUrl: "https://bigbasket.com/careers/security",
    description: "Secure our web and mobile applications from end to end. You'll perform regular security audits, conduct penetration testing, and help developers write more secure code."
  },
  {
    id: "job-039",
    title: "Operations Manager",
    company: "Delhivery",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "3-5",
    skills: ["Logistics", "Process Optimization", "Management"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "15–22 LPA",
    applyUrl: "https://delhivery.com/careers/ops-mgr",
    description: "Lead our logistics operations and ensure timely deliveries. You'll manage a large team and focus on optimizing processes to improve efficiency and reduce costs. 3+ years in ops required."
  },
  {
    id: "job-040",
    title: "Android Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java/Kotlin", "XML", "API Integration"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://meesho.com/careers/intern",
    description: "Learn how to build and maintain an e-commerce platform that reaches every corner of India. You'll work on Android features that empower local business owners. High growth environment."
  },
  {
    id: "job-041",
    title: "Technical Lead",
    company: "ClearTax",
    location: "Bangalore",
    mode: "Onsite",
    experience: "5+",
    skills: ["Architectural Design", "Mentoring", "System Scale"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "40–60 LPA",
    applyUrl: "https://cleartax.in/careers/tech-lead",
    description: "Lead a high-performance engineering team and define our technical roadmap. You'll oversee the architecture of our tax and finance products and ensure they scale smoothly. 5+ years of experience."
  },
  {
    id: "job-042",
    title: "Full Stack Intern",
    company: "Vedantu",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Node.js", "React", "NoSQL"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://vedantu.com/careers/intern",
    description: "Support our engineering team in building the next generation of online learning tools. You'll work on both frontend and backend tasks. Great opportunity to learn full-stack development."
  },
  {
    id: "job-043",
    title: "DevOps Engineer",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Kubernetes", "CI/CD", "AWS", "Grafana"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "20–30 LPA",
    applyUrl: "https://postman.com/careers/devops",
    description: "Join the team that is building the world's most popular API platform. You'll work on scaling our cloud infrastructure and automating our deployment pipelines. Passion for developer experience."
  },
  {
    id: "job-044",
    title: "Business Development Associate",
    company: "BYJU'S",
    location: "Pan India",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Sales", "Presentation", "Target-oriented"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "5–8 LPA",
    applyUrl: "https://byjus.com/careers/bda",
    description: "Become a brand ambassador for BYJU'S and help students choose the right learning path. You'll be responsible for lead generation and closing sales. Looking for highly motivated freshers."
  },
  {
    id: "job-045",
    title: "Product Analyst",
    company: "Vymo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Analytics", "Mixpanel", "SQL", "Product Sense"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "9–14 LPA",
    applyUrl: "https://vymo.com/careers/analyst",
    description: "Analyze product usage data to identify growth opportunities and improve user experience. You'll work closely with PMs and designers. Strong analytical and communication skills are required."
  },
  {
    id: "job-046",
    title: "Java Intern",
    company: "Amdocs",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java Core", "Spring", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://amdocs.com/careers/intern",
    description: "Learn how to build carrier-grade software for the communications industry. You'll be mentored by experienced Java developers and work on various small scale features within our products."
  },
  {
    id: "job-047",
    title: "Cloud Operations Intern",
    company: "HCLTech",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["AWS/Azure", "Linux", "Troubleshooting"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹12k–₹18k/month Internship",
    applyUrl: "https://hcltech.com/careers/cloud-intern",
    description: "Get started in a career in cloud computing. You'll assist our cloud ops team in monitoring and managing client environments. Looking for candidates with basic understanding of cloud and Linux."
  },
  {
    id: "job-048",
    title: "Salesforce Developer",
    company: "PwC India",
    location: "Kolkata",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Apex", "LWC", "Aura", "Admin"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "8–14 LPA",
    applyUrl: "https://pwc.in/careers/salesforce",
    description: "Build custom solutions on the Salesforce platform for our clients. You'll write Apex code and create custom Lightning components. Certifications are a plus but not mandatory."
  },
  {
    id: "job-049",
    title: "React Native Developer",
    company: "1mg",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React Native", "JavaScript", "Mobile UX"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "14–20 LPA",
    applyUrl: "https://1mg.com/careers/react-native",
    description: "Join the mobile team at 1mg and help build the most popular healthcare app in India. You'll use React Native to create new features and optimize performance. 1+ years of RN experience required."
  },
  {
    id: "job-050",
    title: "Software Engineer",
    company: "Atlassian",
    location: "Bangalore",
    mode: "Remote",
    experience: "3-5",
    skills: ["Java", "Distributed Systems", "Scaling"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "40–65 LPA",
    applyUrl: "https://atlassian.com/careers/eng",
    description: "Join our global engineering team and build software that helps teams collaborate better. You'll work on high-scale distributed systems and ensure they remain fast and reliable. Looking for expert coders."
  },
  {
    id: "job-051",
    title: "Marketing Intern",
    company: "Nykaa",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Social Media", "Creativity", "Writing"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://nykaa.com/careers/intern",
    description: "Learn the latest in e-commerce marketing at Nykaa. You'll assist our branding and social media teams in creating content and running campaigns. Perfect for students interested in a career in marketing."
  },
  {
    id: "job-052",
    title: "Frontend Developer",
    company: "Lenskart",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "CSS in JS", "Performance"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "12–18 LPA",
    applyUrl: "https://lenskart.com/careers/frontend",
    description: "Build exceptional shopping experiences for Lenskart. You will work on pixel-perfect implementations and ensure our web applications are blazing fast. Looking for engineers with an eye for design."
  },
  {
    id: "job-053",
    title: "Support Engineer (Big Data)",
    company: "Cloudera",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Hadoop", "Spark", "Troubleshooting"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "14–22 LPA",
    applyUrl: "https://cloudera.com/careers/support",
    description: "Help our customers manage their large-scale big data environments. You'll troubleshoot complex issues in Hadoop, Spark, and other ecosystem components. Deep technical knowledge required."
  },
  {
    id: "job-054",
    title: "QA Engineer (Automation)",
    company: "Urban Company",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Selenium", "Appium", "Java/Python"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "10–16 LPA",
    applyUrl: "https://urbancompany.com/careers/qa",
    description: "Lead the automation effort for Urban Company's web and mobile apps. You'll build and maintain test automation frameworks and ensure high quality across all our platforms."
  },
  {
    id: "job-055",
    title: "C++ Developer",
    company: "Nvidia",
    location: "Bangalore",
    mode: "Onsite",
    experience: "3-5",
    skills: ["C++", "CUDA", "GPU Programming"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "30–50 LPA",
    applyUrl: "https://nvidia.com/careers/cpp-dev",
    description: "Join the global leader in GPU computing. You'll write high-performance C++ and CUDA code that powers everything from gaming to AI. Looking for engineers with deep C++ knowledge."
  },
  {
    id: "job-056",
    title: "Data Analyst",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["SQL", "Python", "Data Viz"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "10–15 LPA",
    applyUrl: "https://dunzo.com/careers/analyst",
    description: "Analyze Dunzo's data to improve operational efficiency and customer experience. You'll work on everything from delivery optimization to marketing analytics. Strong data sense required."
  },
  {
    id: "job-057",
    title: "Information Security Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Networks", "Basic Security", "Vulnerability"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://flipkart.com/careers/security-intern",
    description: "Learn how a major e-commerce company protects its data. You'll assist our security team in various auditing and monitoring tasks. Perfect for students interested in a career in cybersecurity."
  },
  {
    id: "job-058",
    title: "Product Intern",
    company: "Khatabook",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["User Discovery", "Market Research", "Docs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://khatabook.com/careers/product-intern",
    description: "Support our product team in understanding our users - the small store owners of India. You'll conduct interviews, analyze feedback, and help define features that solve their problems."
  },
  {
    id: "job-059",
    title: "Legal Associate (Corporate)",
    company: "Luthra and Luthra",
    location: "Mumbai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Corporate Law", "Drafting", "Research"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "12–18 LPA",
    applyUrl: "https://luthra.com/careers",
    description: "Join one of India's leading law firms. You will work on various corporate advisory and transaction matters. Looking for graduates from top law schools with a strong academic record."
  },
  {
    id: "job-060",
    title: "Software Engineer (New Grad)",
    company: "Google",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java/C++/Python", "Algorithms", "Scale"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "30–45 LPA",
    applyUrl: "https://google.com/careers/university",
    description: "Join Google as a New Grad SDE and work on products that impact billions. You'll join a world-class team and solve some of the toughest problems in computer science. Strong algorithmic skills required."
  }
];
